### ISSUE TITLE
Allow package list to be overridden

### ISSUE THREAD

**Issue by adoom42** [anderssh/ash-netbox#11]
I manage several packages such as gcc on my own through other modules.  The netbox module throws a duplicate definition error because it also tries to manage them:
https://github.com/anderssh/ash-netbox/blob/f887d1b490f1ee665df064d541bdbff9bc0b89fe/manifests/install.pp#L82-L91

Please change the $packages variable from a static list to a class parameter so it can be overridden with a custom list.  Same goes for other static variables such as $ldap_packages.

Also consider using `ensure_packages()` from [stdlib](https://github.com/puppetlabs/puppetlabs-stdlib/blob/main/REFERENCE.md#ensure_packages).

**Comment by lukebigum** [comment]
I've changed it to `ensure_packages` in #14
