### ISSUE TITLE
exec corrective change is applied at every puppet run

### ISSUE THREAD

**Issue by BirgerM** [anderssh/ash-netbox#7]
What is expected?
When the archive is extracted this should notify the exec to set the correct permissions.

What happens?
Exec runs even when there are no changes to the archive.

What should be done?
In install.pp the exec should be modified to only be applied when the archive is extracted.

Change from:
```
exec { 'netbox permission':
    command   => "chown -R ${user}:${group} ${software_directory_with_version}",
    path      => ['/usr/bin'],
    subscribe => Archive[$local_tarball],
}
```
to:
```
exec { 'netbox permission':
    command     => "chown -R ${user}:${group} ${software_directory_with_version}",
    path        => ['/usr/bin'],
    subscribe   => Archive[$local_tarball],
    refreshonly => true,
}
```

**Comment by anderssh** [comment]
resolved in version 2.01
