### ISSUE TITLE
Default encoding to UTF8

### ISSUE THREAD

**Issue by imp1sh** [anderssh/ash-netbox#8]
Hi,
we are using your puppet module, thank you.
The default encoding seems to be ASCII. When we bulk import csv data we get encoding errors, since we have special characters in our data.

Please consider changing the default encoding to UTF8

**Comment by anderssh** [comment]
Hi,
I am happy to change this.
The easiest way to fix this is by submitting a PR, but if you are not able/willing to do that, I will look into it. 

Can you provide a little more information? Are you talking about the encoding in the postgreSQL database?

**Comment by imp1sh** [comment]
I refer to the Postgresql database.
This is an example to set it within the postgresql module which I believe you're using:
```
class { 'postgresql::globals':
  encoding => 'UTF-8',
  locale   => 'en_US.UTF-8',
}
```
It's explained here:
[](https://forge.puppet.com/puppetlabs/postgresql)
